#!/usr/bin/env python2
# -*- python -*-
#
# The CERNBox Project.
#
# Author: 
# License: AGPL
#
#$Id: $
#
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Perform internal setup of the environment.
# This is a Copy/Paste logic which must stay in THIS file
def standardSetup():
   import sys, os.path
   # insert the path to cernafs based on the relative position of this scrip inside the service directory tree
   exeDir = os.path.abspath(os.path.normpath(os.path.dirname(sys.argv[0])))
   pythonDir = os.path.join(exeDir, 'python' )
   sys.path.insert(0, pythonDir)
   import cernbox_utils.setup
   cernbox_utils.setup.standardSetup(sys.argv[0]) # execute a setup hook

standardSetup()
del standardSetup
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

config = None
logger = None

eos = None # EOS interface instance
db = None # DB interface instance

import cernbox_utils

import os, os.path, sys
import subprocess

def main():
   global config,logger
   import cernbox_utils.script
   from cernbox_utils.eos import is_special_folder

   parser=cernbox_utils.script.arg_parser(description='Manipulate SWAN projects.')
   subparser = parser.add_subparsers(title='command',dest='cmd')

   subcmd = subparser.add_parser('list-shared-by', help="list all SWAN projects shared by the user")
   subcmd.add_argument("user", help="specify owner")
   subcmd.add_argument("--project", default=None, action='store', help="specify particular project to list")   

   subcmd = subparser.add_parser('list-shared-with', help="list all SWAN projects shared with the user")
   subcmd.add_argument("user", help="specify sharee")

   subcmd = subparser.add_parser('update-share', help="update share for a SWAN project which will be shared to the specified sharees (and only to them)")
   subcmd.add_argument("owner", help="share owner")
   subcmd.add_argument("project", help="project path")
   subcmd.add_argument("sharees", help="specify sharees",nargs='+')

   subcmd = subparser.add_parser('delete-share', help="delete all shares for a SWAN project")
   subcmd.add_argument("owner", help="share owner")
   subcmd.add_argument("project", help="project path")

   args = parser.parse_args()

   config = cernbox_utils.script.configure(args.config)

   logger = cernbox_utils.script.getLogger(level=args.loglevel)

   logger.info("Using  DB: %s",config['dbhost'])
   logger.info("Using EOS: %s",config['eos_mgm_url'])

   global eos,db
   import cernbox_utils.db, cernbox_utils.eos
   db = cernbox_utils.db.ShareDB()
   eos = cernbox_utils.eos.EOS(config['eos_mgm_url'])
   eos.role=(0,0)


   def print_json(obj):
       if args.json:
           import json
           print json.dumps(obj,ensure_ascii=False) # allows unicode characters from eos output

   def print_json_error(msg):
       print_json({"error" : str(msg)})


   f = globals()['cmd_'+args.cmd.replace('-','_')]

   try:
       r = f(args)
       print_json(r)
#   except CmdBadRequestError,x:
#       print_json_error(x.msg)
#       sys.exit(3)
   except Exception,x:
       raise
       sys.exit(2)

def cmd_update_share(args):
   parse_swan_project(args.project)
   return _cmd_swan_update_share(args.project, args.owner, args.sharees)

def cmd_delete_share(args):
   parse_swan_project(args.project)
   return _cmd_swan_update_share(args.project, args.owner, [])

def _cmd_swan_update_share(swan_project, owner, sharees):
   import cernbox_utils.sharing

   for sharee in sharees:
      cernbox_utils.sharing.check_can_share(owner,sharee)

   f = get_swan_project_fileinfo(owner, swan_project)

   shares=db.get_share(owner=owner,fid=f.ino)

   sharees_requested = [ cernbox_utils.sharing.split_sharee(x)[1] for x in sharees ]

   # PENDING: this should be a DB TRANSACTION!

   db_update_cnt = 0

   for s in shares:
      if s.share_with not in sharees_requested:
         db.delete_share(s.id)
         db_update_cnt += 1

   sharees_existing = [ s.share_with for s in shares ]

   for sharee in sharees:
      if cernbox_utils.sharing.split_sharee(sharee)[1] not in sharees_existing:
         cernbox_utils.sharing.add_share(owner,f.file,sharee,"r",eos,db,config,storage_acl_update=False)
         db_update_cnt += 1

   try:
      logger.info("Updated %d share entries",db_update_cnt)

      if db_update_cnt:
         # modify storage ACL      
         cernbox_utils.sharing.update_acls(f.ino,eos,db,owner,dryrun=False)

   except Exception,x:
      logger.critical("Something went pretty wrong... %s %s",hash(x),x)
      #rollback the insert?
      raise

def cmd_list_shared_with(args):    
    return _cmd_list_shared(args,"sharee",None)

def cmd_list_shared_by(args):

    if args.project:
        parse_swan_project(args.project)
        f = get_swan_project_fileinfo(args.user,args.project)
        inode=f.ino
    else:
        inode = None
    
    return _cmd_list_shared(args,"owner",inode)

def _cmd_list_shared(args,role,inode):
   import cernbox_utils.sharing

   retbuf = cernbox_utils.sharing.list_shares(args.user,role,inode,False,False,db,eos)

   retobj = []
   
   for x in retbuf:

      swanprj = path2swanprj(x['path'])

      if swanprj:
         x['project']=swanprj
         retobj.append(x)

   return {'shares':retobj}


# helpers

def get_swan_project_fileinfo(owner,swan_project):

      p = swanprj2path(owner,swan_project)

      if not p:
         print_json_error("Project name misformatted: %s"%(swan_project))
         sys.exit(2) # TODO: FIX RC => 400 Bad Request

      try:
         return cernbox_utils.sharing.check_share_target(p,owner,eos,config)
      except  subprocess.CalledProcessError,x:
         if x.returncode == 2:
            print_json_error("Project not found: %s owner %s"%(swan_project,owner))
            sys.exit(2) 
         else:
            raise


def parse_swan_project(swanprj):
   if not is_swanprj(swanprj):
      print >> sys.stderr, "ERROR: SWAN project name wrongly specified '%s'"% (swanprj)
      sys.exit(2)

# convert SWAN project name to EOS path and vice-versa

def is_swanprj(pname):
   p = os.path.split(os.path.normpath(pname))
   return len(p)==2 and p[0]=='SWAN_projects'

def swanprj2path(owner,pname):
   if not is_swanprj(pname):
      return None
   else:
      return os.path.join(config['eos_prefix'],owner[0],owner,pname)

def path2swanprj(path):
   if not path.startswith(config['eos_prefix']):
      return None

   p = os.path.normpath(path[len(config['eos_prefix']):])

   p = "/".join(p.split('/')[2:])

   if is_swanprj(p):
      return p
   else:
      return None

def unit_test_swanprj():

   print "--- UNIT TEST SWANPRJ: BEGIN"

   assert(os.path.normpath(config['eos_prefix']) == '/eos/scratch/user')

   print is_swanprj("SWAN_projects/X") # => True
   print is_swanprj("SWAN_projects/X/Y") # => False
   print is_swanprj("SWAN_projects/") # => False
   print is_swanprj("SWAN_projects") # => False
   print is_swanprj("X") # => False
   print is_swanprj("") # => False

   print swanprj2path('moscicki',"X") # => None
   print swanprj2path('moscicki',"SWAN_projects/X") # => /eos/scratch/user/m/moscicki/SWAN_projects/X

   print path2swanprj("/eos/scratch/user/m/moscicki/SWAN_projects/X") # => SWAN_projects/X

   print "--- UNIT TEST SWANPRJ: END"


if __name__ == "__main__":
   sys.exit(main())
